# Generated by Django 6.0.4 on 2026-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_vendorcompany_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmaster',
            name='rvb_candidate',
            field=models.BooleanField(default=False, help_text='Flagged as a rent-vs-buy candidate based on market rate comparison.'),
        ),
        migrations.AddField(
            model_name='vendoraudit',
            name='no_change',
            field=models.BooleanField(default=False, help_text='Vendor explicitly declared no changes for this cycle.'),
        ),
        migrations.AddField(
            model_name='vendoraudit',
            name='no_change_declared_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when vendor submitted the No Changes declaration.', null=True),
        ),
        migrations.CreateModel(
            name='EquipmentMarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_description', models.CharField(help_text='Equipment type label matching rental_master equipment_description.', max_length=255)),
                ('equipment_category', models.CharField(blank=True, max_length=120)),
                ('estimated_purchase_price', models.DecimalField(decimal_places=2, help_text='Estimated purchase price (USD) for this equipment type.', max_digits=14)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5, help_text='Expected useful life in years for straight-line cost comparison.')),
                ('market_daily_rate', models.DecimalField(decimal_places=2, help_text='Current market daily rental rate benchmark (USD).', max_digits=12)),
                ('rvb_daily_threshold', models.DecimalField(decimal_places=2, help_text='Daily cost above which renting exceeds straight-line ownership cost.', max_digits=12)),
                ('effective_date', models.DateField(help_text='Date this rate record became effective.')),
                ('source_notes', models.TextField(blank=True, help_text='Rate source or reference.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['equipment_description', '-effective_date'],
                'indexes': [models.Index(fields=['equipment_description'], name='rentals_equ_equipme_515cfc_idx')],
            },
        ),
    ]
