# Generated by Django 6.0.4 on 2026-04-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentalmaster_rvb_candidate_vendoraudit_no_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmaster',
            name='po_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='rentalmaster',
            name='sn_request_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='rentalstaging',
            name='po_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='rentalstaging',
            name='sn_request_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
