# Generated by Django 6.0.4 on 2026-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rentalmaster_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmaster',
            name='cycle_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalmaster',
            name='cycle_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalstaging',
            name='cycle_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalstaging',
            name='cycle_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
