# Generated by Django 6.0.4 on 2026-04-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentalmaster_cycle_week_rentalmaster_cycle_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmarketrate',
            name='rvb_monthly_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly cost above which renting exceeds straight-line ownership cost (purchase_price / useful_life_years / 12).', max_digits=12),
        ),
    ]
