# Generated by Django 6.0.4 on 2026-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_equipmentmarketrate_monthly_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmarketrate',
            name='annual_maintenance_pct',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Estimated annual maintenance cost as a fraction of purchase price (e.g. 0.12 = 12%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='equipmentmarketrate',
            name='monthly_maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated monthly maintenance cost = purchase_price × annual_maintenance_pct / 12.', max_digits=12),
        ),
    ]
