# Generated by Django 6.0.4 on 2026-04-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_equipmentmarketrate_maintenance_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmaster',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalstaging',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
