# Generated by Django 6.0.4 on 2026-04-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_userprofile_external_user_and_staff_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='PODepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=80, unique=True)),
                ('department', models.CharField(choices=[('Coke', 'Coke'), ('Iron', 'Iron'), ('Steel', 'Steel'), ('Plate', 'Plate'), ('Hot Mill', 'Hot Mill'), ('Cold Mill', 'Cold Mill'), ('MEU', 'MEU')], default='Coke', max_length=20)),
            ],
            options={
                'verbose_name': 'PO Department',
                'verbose_name_plural': 'PO Departments',
                'ordering': ['po_number'],
            },
        ),
    ]
