# Generated by Django 6.0.4 on 2026-04-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_po_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmaster',
            name='equipment_category',
            field=models.CharField(blank=True, help_text='Equipment category (e.g., Wheel Loader, Light Tower) from EquipmentMarketRate.', max_length=120),
        ),
    ]
