# Generated by Django 6.0.4 on 2026-04-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_add_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalstaging',
            name='equipment_category',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
