# Generated by Django 6.0.4 on 2026-04-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_add_equipment_category_to_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedEquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Approved Equipment Category',
                'verbose_name_plural': 'Approved Equipment Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
