# Generated by Django 6.0.4 on 2026-05-01 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_add_login_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedequipmentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Approved Equipment Category', 'verbose_name_plural': 'Approved Equipment Categories'},
        ),
        migrations.RemoveField(
            model_name='approvedequipmentcategory',
            name='sort_order',
        ),
    ]
