# Generated by Django 6.0.4 on 2026-05-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_remove_sort_order_from_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcompany',
            name='cadence',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Expected submission frequency for this vendor.', max_length=20),
        ),
    ]
